// Generated by CoffeeScript 1.8.0
(function() {
  describe("Featurette", function() {
    it("registers featurettes", function() {
      return expect(Featurette.registered_features["exclamation"]).toBeDefined();
    });
    it("executes features when load is run", function() {
      var element;
      Featurette.load();
      element = document.getElementsByTagName("h1")[0];
      return expect(element.innerHTML).toEqual("Exclamation!");
    });
    it("executes multiple features when load is run", function() {
      var element;
      Featurette.load();
      element = document.getElementsByTagName("h2")[0];
      return expect(element.innerHTML).toEqual("Wondered!?");
    });
    it("gives ids to featurettes without them", function() {
      var element;
      element = document.getElementsByTagName("h1")[0];
      return expect(element.id.indexOf("featurette-")).toEqual(0);
    });
    it("doesn't give ids to features with them", function() {
      var element;
      element = document.getElementById("so-awesome");
      return expect(element.innerHTML).toEqual("So awesome!");
    });
    describe("calling load subsequent times", function() {
      it("ignores featurettes that have already loaded", function() {
        var element, list;
        list = document.getElementById("exclamatory-list");
        list.innerHTML = "<li id=\"so-cool\" data-featurette=\"exclamation\">So cool</li>";
        Featurette.load();
        element = document.getElementsByTagName("h1")[0];
        return expect(element.innerHTML).toEqual("Exclamation!");
      });
      return it("loads unloaded featurettes", function() {
        var element;
        element = document.getElementById("so-cool");
        return expect(element.innerHTML).toEqual("So cool!");
      });
    });
    describe("calling Featurette.load inside a featurette's constructor", function() {
      return it("doesn't make the world implode", function() {
        return expect(Featurette.get('boom')).toBeDefined();
      });
    });
    return describe("Retrieving a featurette", function() {
      it("retrieves with id and params", function() {
        return expect(Featurette.get('multiple', {
          index: 1
        })).toBeDefined();
      });
      return it("retrieves with id and invalid params", function() {
        return expect(Featurette.get('multiple', {
          index: 2
        })).toBeUndefined();
      });
    });
  });

}).call(this);
